### ISSUE TITLE
Test: DNA.db with manual scan datetime override

### ISSUE THREAD

**Issue by infamousjoeg** [infamousjoeg/DNAmicAnalysis#110]

**Comment by infamousjoeg** [comment]
```yaml
database_file: data/test/DNA.db
...
scan_datetime:
  override: yes
  manual_scan_datetime: "2019-05-21 20:57:43"
```

Tested successfully!
